services:
  ui:
    image: nginx:1.27.0-alpine-otel
    volumes:
      - ./examples/ui:/usr/share/nginx/html:ro
      - ./examples/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./examples/certs/ui.crt:/etc/nginx/ui.crt:ro
      - ./examples/certs/ui.key:/etc/nginx/ui.key:ro
    depends_on:
      - control
      - request
      - cargo
      - engine
      - inventory
    ports:
      - 8888:443

  cargo:
    image: stoke-ex/python-grpc
    build:
      context: .
      dockerfile: ./examples/cargo/Dockerfile

  control:
    image: stoke-ex/go-rest
    build:
      context: .
      dockerfile: ./examples/control/Dockerfile
    depends_on:
      - engine
    environment:
      - ENGINE_URL=engine:6060
    ports:
      - 8001:8080

  engine:
    image: stoke-ex/go-grpc
    build:
      context: .
      dockerfile: ./examples/engine/Dockerfile

  inventory:
    image: stoke-ex/python-django
    build:
      context: .
      dockerfile: ./examples/inventory/Dockerfile
    ports:
      - 8002:8080

  request:
    image: stoke-ex/python-flask
    build:
      context: .
      dockerfile: ./examples/request/Dockerfile
    ports:
      - 8003:8080

