services:
  ui:
    image: nginx:1.27.0-alpine-otel
    volumes:
      - ./examples/ui:/usr/share/nginx/html:ro
      - ./examples/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - control
      - request
    ports:
      - 8888:80

#  cargo:
#    image: stoke-ex/python-grpc
#    build: ./examples/cargo/

  control:
    image: stoke-ex/go-rest
    build:
      context: .
      dockerfile: ./examples/control/Dockerfile
    depends_on:
      - engine
    environment:
      - ENGINE_URL=engine:6060

  engine:
    image: stoke-ex/go-grpc
    build:
      context: .
      dockerfile: ./examples/engine/Dockerfile

#  inventory:
#    image: stoke-ex/python-django
#    build: ./examples/inventory/

  request:
    image: stoke-ex/python-flask
    build:
      context: .
      dockerfile: ./examples/request/Dockerfile

