issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/ent/
      linters:
        - errcheck
    - path: internal/schema/
      linters:
        - errcheck
run:
  timeout: 5m
