apiVersion: v1
kind: Service
metadata:
  name: stoke-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: stoke
    app.kubernetes.io/component: service
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: stoke
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.server.port }}
