
export default {
  CLAIM: "mdi-book-lock",
  USER: "mdi-account",
  GROUP: "mdi-folder",
  CLAIM_SEARCH: "mdi-book-search",
  USER_SEARCH: "mdi-account-search",
  GROUP_SEARCH: "mdi-folder-search",
  LOCAL: "mdi-account-cowboy-hat",
  LINK: "mdi-link-variant",
  ADD_LINK: "mdi-link-variant-plus",
  DELETE_LINK: "mdi-link-variant-remove",
  MAIL: "mdi-mail",
  PIN_ON: "mdi-pin",
  PIN_OFF: "mdi-pin-off",
  LOGOUT: "mdi-logout",
  MONITOR: "mdi-chart-line",
  KEYS: "mdi-key-chain",
  EDIT: "mdi-pencil",
  ADD:  "mdi-plus",
  DELETE: "mdi-trash-can",
}
