// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"stoke/internal/ent/claim"
	"stoke/internal/ent/claimgroup"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClaimCreate is the builder for creating a Claim entity.
type ClaimCreate struct {
	config
	mutation *ClaimMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (cc *ClaimCreate) SetName(s string) *ClaimCreate {
	cc.mutation.SetName(s)
	return cc
}

// SetShortName sets the "short_name" field.
func (cc *ClaimCreate) SetShortName(s string) *ClaimCreate {
	cc.mutation.SetShortName(s)
	return cc
}

// SetDescription sets the "description" field.
func (cc *ClaimCreate) SetDescription(s string) *ClaimCreate {
	cc.mutation.SetDescription(s)
	return cc
}

// AddClaimGroupIDs adds the "claim_groups" edge to the ClaimGroup entity by IDs.
func (cc *ClaimCreate) AddClaimGroupIDs(ids ...int) *ClaimCreate {
	cc.mutation.AddClaimGroupIDs(ids...)
	return cc
}

// AddClaimGroups adds the "claim_groups" edges to the ClaimGroup entity.
func (cc *ClaimCreate) AddClaimGroups(c ...*ClaimGroup) *ClaimCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cc.AddClaimGroupIDs(ids...)
}

// Mutation returns the ClaimMutation object of the builder.
func (cc *ClaimCreate) Mutation() *ClaimMutation {
	return cc.mutation
}

// Save creates the Claim in the database.
func (cc *ClaimCreate) Save(ctx context.Context) (*Claim, error) {
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ClaimCreate) SaveX(ctx context.Context) *Claim {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ClaimCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ClaimCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ClaimCreate) check() error {
	if _, ok := cc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Claim.name"`)}
	}
	if _, ok := cc.mutation.ShortName(); !ok {
		return &ValidationError{Name: "short_name", err: errors.New(`ent: missing required field "Claim.short_name"`)}
	}
	if _, ok := cc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Claim.description"`)}
	}
	return nil
}

func (cc *ClaimCreate) sqlSave(ctx context.Context) (*Claim, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ClaimCreate) createSpec() (*Claim, *sqlgraph.CreateSpec) {
	var (
		_node = &Claim{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(claim.Table, sqlgraph.NewFieldSpec(claim.FieldID, field.TypeInt))
	)
	if value, ok := cc.mutation.Name(); ok {
		_spec.SetField(claim.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := cc.mutation.ShortName(); ok {
		_spec.SetField(claim.FieldShortName, field.TypeString, value)
		_node.ShortName = value
	}
	if value, ok := cc.mutation.Description(); ok {
		_spec.SetField(claim.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := cc.mutation.ClaimGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   claim.ClaimGroupsTable,
			Columns: claim.ClaimGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claimgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClaimCreateBulk is the builder for creating many Claim entities in bulk.
type ClaimCreateBulk struct {
	config
	err      error
	builders []*ClaimCreate
}

// Save creates the Claim entities in the database.
func (ccb *ClaimCreateBulk) Save(ctx context.Context) ([]*Claim, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Claim, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClaimMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ClaimCreateBulk) SaveX(ctx context.Context) []*Claim {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ClaimCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ClaimCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
