// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"stoke/internal/ent/claim"
	"stoke/internal/ent/claimgroup"
	"stoke/internal/ent/grouplink"
	"stoke/internal/ent/predicate"
	"stoke/internal/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClaimGroupQuery is the builder for querying ClaimGroup entities.
type ClaimGroupQuery struct {
	config
	ctx            *QueryContext
	order          []claimgroup.OrderOption
	inters         []Interceptor
	predicates     []predicate.ClaimGroup
	withUsers      *UserQuery
	withGroupLinks *GroupLinkQuery
	withClaims     *ClaimQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ClaimGroupQuery builder.
func (cgq *ClaimGroupQuery) Where(ps ...predicate.ClaimGroup) *ClaimGroupQuery {
	cgq.predicates = append(cgq.predicates, ps...)
	return cgq
}

// Limit the number of records to be returned by this query.
func (cgq *ClaimGroupQuery) Limit(limit int) *ClaimGroupQuery {
	cgq.ctx.Limit = &limit
	return cgq
}

// Offset to start from.
func (cgq *ClaimGroupQuery) Offset(offset int) *ClaimGroupQuery {
	cgq.ctx.Offset = &offset
	return cgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cgq *ClaimGroupQuery) Unique(unique bool) *ClaimGroupQuery {
	cgq.ctx.Unique = &unique
	return cgq
}

// Order specifies how the records should be ordered.
func (cgq *ClaimGroupQuery) Order(o ...claimgroup.OrderOption) *ClaimGroupQuery {
	cgq.order = append(cgq.order, o...)
	return cgq
}

// QueryUsers chains the current query on the "users" edge.
func (cgq *ClaimGroupQuery) QueryUsers() *UserQuery {
	query := (&UserClient{config: cgq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(claimgroup.Table, claimgroup.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, claimgroup.UsersTable, claimgroup.UsersPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(cgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroupLinks chains the current query on the "group_links" edge.
func (cgq *ClaimGroupQuery) QueryGroupLinks() *GroupLinkQuery {
	query := (&GroupLinkClient{config: cgq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(claimgroup.Table, claimgroup.FieldID, selector),
			sqlgraph.To(grouplink.Table, grouplink.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, claimgroup.GroupLinksTable, claimgroup.GroupLinksColumn),
		)
		fromU = sqlgraph.SetNeighbors(cgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryClaims chains the current query on the "claims" edge.
func (cgq *ClaimGroupQuery) QueryClaims() *ClaimQuery {
	query := (&ClaimClient{config: cgq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(claimgroup.Table, claimgroup.FieldID, selector),
			sqlgraph.To(claim.Table, claim.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, claimgroup.ClaimsTable, claimgroup.ClaimsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(cgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ClaimGroup entity from the query.
// Returns a *NotFoundError when no ClaimGroup was found.
func (cgq *ClaimGroupQuery) First(ctx context.Context) (*ClaimGroup, error) {
	nodes, err := cgq.Limit(1).All(setContextOp(ctx, cgq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{claimgroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cgq *ClaimGroupQuery) FirstX(ctx context.Context) *ClaimGroup {
	node, err := cgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ClaimGroup ID from the query.
// Returns a *NotFoundError when no ClaimGroup ID was found.
func (cgq *ClaimGroupQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cgq.Limit(1).IDs(setContextOp(ctx, cgq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{claimgroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cgq *ClaimGroupQuery) FirstIDX(ctx context.Context) int {
	id, err := cgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ClaimGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ClaimGroup entity is found.
// Returns a *NotFoundError when no ClaimGroup entities are found.
func (cgq *ClaimGroupQuery) Only(ctx context.Context) (*ClaimGroup, error) {
	nodes, err := cgq.Limit(2).All(setContextOp(ctx, cgq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{claimgroup.Label}
	default:
		return nil, &NotSingularError{claimgroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cgq *ClaimGroupQuery) OnlyX(ctx context.Context) *ClaimGroup {
	node, err := cgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ClaimGroup ID in the query.
// Returns a *NotSingularError when more than one ClaimGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (cgq *ClaimGroupQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cgq.Limit(2).IDs(setContextOp(ctx, cgq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{claimgroup.Label}
	default:
		err = &NotSingularError{claimgroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cgq *ClaimGroupQuery) OnlyIDX(ctx context.Context) int {
	id, err := cgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ClaimGroups.
func (cgq *ClaimGroupQuery) All(ctx context.Context) ([]*ClaimGroup, error) {
	ctx = setContextOp(ctx, cgq.ctx, "All")
	if err := cgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ClaimGroup, *ClaimGroupQuery]()
	return withInterceptors[[]*ClaimGroup](ctx, cgq, qr, cgq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cgq *ClaimGroupQuery) AllX(ctx context.Context) []*ClaimGroup {
	nodes, err := cgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ClaimGroup IDs.
func (cgq *ClaimGroupQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cgq.ctx.Unique == nil && cgq.path != nil {
		cgq.Unique(true)
	}
	ctx = setContextOp(ctx, cgq.ctx, "IDs")
	if err = cgq.Select(claimgroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cgq *ClaimGroupQuery) IDsX(ctx context.Context) []int {
	ids, err := cgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cgq *ClaimGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cgq.ctx, "Count")
	if err := cgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cgq, querierCount[*ClaimGroupQuery](), cgq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cgq *ClaimGroupQuery) CountX(ctx context.Context) int {
	count, err := cgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cgq *ClaimGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cgq.ctx, "Exist")
	switch _, err := cgq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cgq *ClaimGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := cgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ClaimGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cgq *ClaimGroupQuery) Clone() *ClaimGroupQuery {
	if cgq == nil {
		return nil
	}
	return &ClaimGroupQuery{
		config:         cgq.config,
		ctx:            cgq.ctx.Clone(),
		order:          append([]claimgroup.OrderOption{}, cgq.order...),
		inters:         append([]Interceptor{}, cgq.inters...),
		predicates:     append([]predicate.ClaimGroup{}, cgq.predicates...),
		withUsers:      cgq.withUsers.Clone(),
		withGroupLinks: cgq.withGroupLinks.Clone(),
		withClaims:     cgq.withClaims.Clone(),
		// clone intermediate query.
		sql:  cgq.sql.Clone(),
		path: cgq.path,
	}
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "users" edge. The optional arguments are used to configure the query builder of the edge.
func (cgq *ClaimGroupQuery) WithUsers(opts ...func(*UserQuery)) *ClaimGroupQuery {
	query := (&UserClient{config: cgq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cgq.withUsers = query
	return cgq
}

// WithGroupLinks tells the query-builder to eager-load the nodes that are connected to
// the "group_links" edge. The optional arguments are used to configure the query builder of the edge.
func (cgq *ClaimGroupQuery) WithGroupLinks(opts ...func(*GroupLinkQuery)) *ClaimGroupQuery {
	query := (&GroupLinkClient{config: cgq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cgq.withGroupLinks = query
	return cgq
}

// WithClaims tells the query-builder to eager-load the nodes that are connected to
// the "claims" edge. The optional arguments are used to configure the query builder of the edge.
func (cgq *ClaimGroupQuery) WithClaims(opts ...func(*ClaimQuery)) *ClaimGroupQuery {
	query := (&ClaimClient{config: cgq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cgq.withClaims = query
	return cgq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ClaimGroup.Query().
//		GroupBy(claimgroup.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cgq *ClaimGroupQuery) GroupBy(field string, fields ...string) *ClaimGroupGroupBy {
	cgq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ClaimGroupGroupBy{build: cgq}
	grbuild.flds = &cgq.ctx.Fields
	grbuild.label = claimgroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ClaimGroup.Query().
//		Select(claimgroup.FieldName).
//		Scan(ctx, &v)
func (cgq *ClaimGroupQuery) Select(fields ...string) *ClaimGroupSelect {
	cgq.ctx.Fields = append(cgq.ctx.Fields, fields...)
	sbuild := &ClaimGroupSelect{ClaimGroupQuery: cgq}
	sbuild.label = claimgroup.Label
	sbuild.flds, sbuild.scan = &cgq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ClaimGroupSelect configured with the given aggregations.
func (cgq *ClaimGroupQuery) Aggregate(fns ...AggregateFunc) *ClaimGroupSelect {
	return cgq.Select().Aggregate(fns...)
}

func (cgq *ClaimGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cgq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cgq); err != nil {
				return err
			}
		}
	}
	for _, f := range cgq.ctx.Fields {
		if !claimgroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cgq.path != nil {
		prev, err := cgq.path(ctx)
		if err != nil {
			return err
		}
		cgq.sql = prev
	}
	return nil
}

func (cgq *ClaimGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ClaimGroup, error) {
	var (
		nodes       = []*ClaimGroup{}
		_spec       = cgq.querySpec()
		loadedTypes = [3]bool{
			cgq.withUsers != nil,
			cgq.withGroupLinks != nil,
			cgq.withClaims != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ClaimGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ClaimGroup{config: cgq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cgq.withUsers; query != nil {
		if err := cgq.loadUsers(ctx, query, nodes,
			func(n *ClaimGroup) { n.Edges.Users = []*User{} },
			func(n *ClaimGroup, e *User) { n.Edges.Users = append(n.Edges.Users, e) }); err != nil {
			return nil, err
		}
	}
	if query := cgq.withGroupLinks; query != nil {
		if err := cgq.loadGroupLinks(ctx, query, nodes,
			func(n *ClaimGroup) { n.Edges.GroupLinks = []*GroupLink{} },
			func(n *ClaimGroup, e *GroupLink) { n.Edges.GroupLinks = append(n.Edges.GroupLinks, e) }); err != nil {
			return nil, err
		}
	}
	if query := cgq.withClaims; query != nil {
		if err := cgq.loadClaims(ctx, query, nodes,
			func(n *ClaimGroup) { n.Edges.Claims = []*Claim{} },
			func(n *ClaimGroup, e *Claim) { n.Edges.Claims = append(n.Edges.Claims, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cgq *ClaimGroupQuery) loadUsers(ctx context.Context, query *UserQuery, nodes []*ClaimGroup, init func(*ClaimGroup), assign func(*ClaimGroup, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*ClaimGroup)
	nids := make(map[int]map[*ClaimGroup]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(claimgroup.UsersTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(claimgroup.UsersPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(claimgroup.UsersPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(claimgroup.UsersPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*ClaimGroup]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*User](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "users" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (cgq *ClaimGroupQuery) loadGroupLinks(ctx context.Context, query *GroupLinkQuery, nodes []*ClaimGroup, init func(*ClaimGroup), assign func(*ClaimGroup, *GroupLink)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ClaimGroup)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.GroupLink(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(claimgroup.GroupLinksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.claim_group_group_links
		if fk == nil {
			return fmt.Errorf(`foreign-key "claim_group_group_links" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "claim_group_group_links" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cgq *ClaimGroupQuery) loadClaims(ctx context.Context, query *ClaimQuery, nodes []*ClaimGroup, init func(*ClaimGroup), assign func(*ClaimGroup, *Claim)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*ClaimGroup)
	nids := make(map[int]map[*ClaimGroup]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(claimgroup.ClaimsTable)
		s.Join(joinT).On(s.C(claim.FieldID), joinT.C(claimgroup.ClaimsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(claimgroup.ClaimsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(claimgroup.ClaimsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*ClaimGroup]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Claim](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "claims" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (cgq *ClaimGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cgq.querySpec()
	_spec.Node.Columns = cgq.ctx.Fields
	if len(cgq.ctx.Fields) > 0 {
		_spec.Unique = cgq.ctx.Unique != nil && *cgq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cgq.driver, _spec)
}

func (cgq *ClaimGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(claimgroup.Table, claimgroup.Columns, sqlgraph.NewFieldSpec(claimgroup.FieldID, field.TypeInt))
	_spec.From = cgq.sql
	if unique := cgq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cgq.path != nil {
		_spec.Unique = true
	}
	if fields := cgq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, claimgroup.FieldID)
		for i := range fields {
			if fields[i] != claimgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cgq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cgq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cgq *ClaimGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cgq.driver.Dialect())
	t1 := builder.Table(claimgroup.Table)
	columns := cgq.ctx.Fields
	if len(columns) == 0 {
		columns = claimgroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cgq.sql != nil {
		selector = cgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cgq.ctx.Unique != nil && *cgq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cgq.predicates {
		p(selector)
	}
	for _, p := range cgq.order {
		p(selector)
	}
	if offset := cgq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cgq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ClaimGroupGroupBy is the group-by builder for ClaimGroup entities.
type ClaimGroupGroupBy struct {
	selector
	build *ClaimGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cggb *ClaimGroupGroupBy) Aggregate(fns ...AggregateFunc) *ClaimGroupGroupBy {
	cggb.fns = append(cggb.fns, fns...)
	return cggb
}

// Scan applies the selector query and scans the result into the given value.
func (cggb *ClaimGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cggb.build.ctx, "GroupBy")
	if err := cggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClaimGroupQuery, *ClaimGroupGroupBy](ctx, cggb.build, cggb, cggb.build.inters, v)
}

func (cggb *ClaimGroupGroupBy) sqlScan(ctx context.Context, root *ClaimGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cggb.fns))
	for _, fn := range cggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cggb.flds)+len(cggb.fns))
		for _, f := range *cggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ClaimGroupSelect is the builder for selecting fields of ClaimGroup entities.
type ClaimGroupSelect struct {
	*ClaimGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cgs *ClaimGroupSelect) Aggregate(fns ...AggregateFunc) *ClaimGroupSelect {
	cgs.fns = append(cgs.fns, fns...)
	return cgs
}

// Scan applies the selector query and scans the result into the given value.
func (cgs *ClaimGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgs.ctx, "Select")
	if err := cgs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClaimGroupQuery, *ClaimGroupSelect](ctx, cgs.ClaimGroupQuery, cgs, cgs.inters, v)
}

func (cgs *ClaimGroupSelect) sqlScan(ctx context.Context, root *ClaimGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cgs.fns))
	for _, fn := range cgs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cgs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
