// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"stoke/internal/ent/predicate"
	"stoke/internal/ent/privatekey"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PrivateKeyUpdate is the builder for updating PrivateKey entities.
type PrivateKeyUpdate struct {
	config
	hooks    []Hook
	mutation *PrivateKeyMutation
}

// Where appends a list predicates to the PrivateKeyUpdate builder.
func (pku *PrivateKeyUpdate) Where(ps ...predicate.PrivateKey) *PrivateKeyUpdate {
	pku.mutation.Where(ps...)
	return pku
}

// Mutation returns the PrivateKeyMutation object of the builder.
func (pku *PrivateKeyUpdate) Mutation() *PrivateKeyMutation {
	return pku.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pku *PrivateKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pku.sqlSave, pku.mutation, pku.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pku *PrivateKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := pku.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pku *PrivateKeyUpdate) Exec(ctx context.Context) error {
	_, err := pku.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pku *PrivateKeyUpdate) ExecX(ctx context.Context) {
	if err := pku.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pku *PrivateKeyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(privatekey.Table, privatekey.Columns, sqlgraph.NewFieldSpec(privatekey.FieldID, field.TypeInt))
	if ps := pku.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pku.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{privatekey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pku.mutation.done = true
	return n, nil
}

// PrivateKeyUpdateOne is the builder for updating a single PrivateKey entity.
type PrivateKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PrivateKeyMutation
}

// Mutation returns the PrivateKeyMutation object of the builder.
func (pkuo *PrivateKeyUpdateOne) Mutation() *PrivateKeyMutation {
	return pkuo.mutation
}

// Where appends a list predicates to the PrivateKeyUpdate builder.
func (pkuo *PrivateKeyUpdateOne) Where(ps ...predicate.PrivateKey) *PrivateKeyUpdateOne {
	pkuo.mutation.Where(ps...)
	return pkuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pkuo *PrivateKeyUpdateOne) Select(field string, fields ...string) *PrivateKeyUpdateOne {
	pkuo.fields = append([]string{field}, fields...)
	return pkuo
}

// Save executes the query and returns the updated PrivateKey entity.
func (pkuo *PrivateKeyUpdateOne) Save(ctx context.Context) (*PrivateKey, error) {
	return withHooks(ctx, pkuo.sqlSave, pkuo.mutation, pkuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pkuo *PrivateKeyUpdateOne) SaveX(ctx context.Context) *PrivateKey {
	node, err := pkuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pkuo *PrivateKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := pkuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pkuo *PrivateKeyUpdateOne) ExecX(ctx context.Context) {
	if err := pkuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pkuo *PrivateKeyUpdateOne) sqlSave(ctx context.Context) (_node *PrivateKey, err error) {
	_spec := sqlgraph.NewUpdateSpec(privatekey.Table, privatekey.Columns, sqlgraph.NewFieldSpec(privatekey.FieldID, field.TypeInt))
	id, ok := pkuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PrivateKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pkuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, privatekey.FieldID)
		for _, f := range fields {
			if !privatekey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != privatekey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pkuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &PrivateKey{config: pkuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pkuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{privatekey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pkuo.mutation.done = true
	return _node, nil
}
