// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Claim is the predicate function for claim builders.
type Claim func(*sql.Selector)

// ClaimGroup is the predicate function for claimgroup builders.
type ClaimGroup func(*sql.Selector)

// GroupLink is the predicate function for grouplink builders.
type GroupLink func(*sql.Selector)

// PrivateKey is the predicate function for privatekey builders.
type PrivateKey func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
