version: "3"

services:
  jeager:
    image: jaegertracing/all-in-one:1.56
    environment:
      - METRICS_STORAGE_TYPE=prometheus
    ports:
      - 0.0.0.0:4317:4317
      - 0.0.0.0:8000:16686
      - 14269:14269
  ldap_test:
    image: ghcr.io/rroemhild/docker-test-openldap:master
    ports:
      - 10389:10389
      - 10636:10636
