// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateClaimGroupRes interface {
	createClaimGroupRes()
}

type CreateClaimRes interface {
	createClaimRes()
}

type CreateGroupLinkRes interface {
	createGroupLinkRes()
}

type DeleteClaimGroupRes interface {
	deleteClaimGroupRes()
}

type DeleteClaimRes interface {
	deleteClaimRes()
}

type DeleteGroupLinkRes interface {
	deleteGroupLinkRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type ListClaimClaimGroupsRes interface {
	listClaimClaimGroupsRes()
}

type ListClaimGroupClaimsRes interface {
	listClaimGroupClaimsRes()
}

type ListClaimGroupGroupLinksRes interface {
	listClaimGroupGroupLinksRes()
}

type ListClaimGroupRes interface {
	listClaimGroupRes()
}

type ListClaimGroupUsersRes interface {
	listClaimGroupUsersRes()
}

type ListClaimRes interface {
	listClaimRes()
}

type ListGroupLinkRes interface {
	listGroupLinkRes()
}

type ListPrivateKeyRes interface {
	listPrivateKeyRes()
}

type ListUserClaimGroupsRes interface {
	listUserClaimGroupsRes()
}

type ListUserRes interface {
	listUserRes()
}

type ReadClaimGroupRes interface {
	readClaimGroupRes()
}

type ReadClaimRes interface {
	readClaimRes()
}

type ReadGroupLinkClaimGroupRes interface {
	readGroupLinkClaimGroupRes()
}

type ReadGroupLinkRes interface {
	readGroupLinkRes()
}

type ReadPrivateKeyRes interface {
	readPrivateKeyRes()
}

type ReadUserRes interface {
	readUserRes()
}

type UpdateClaimGroupRes interface {
	updateClaimGroupRes()
}

type UpdateClaimRes interface {
	updateClaimRes()
}

type UpdateGroupLinkRes interface {
	updateGroupLinkRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
